-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 08:19:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema greenhouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema greenhouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greenhouse` DEFAULT CHARACTER SET utf8 ;
USE `greenhouse` ;

-- -----------------------------------------------------
-- Table `greenhouse`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sensors` TINYINT NOT NULL,
  `actuators` TINYINT NOT NULL,
  `readplot` TINYINT NOT NULL,
  `writeplot` TINYINT NOT NULL,
  `readgreenhouse` TINYINT NOT NULL,
  `writegreenhouse` TINYINT NOT NULL,
  `readusers` TINYINT NOT NULL,
  `writeusers` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` TEXT NOT NULL,
  `permissions` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_permissions_idx` (`permissions` ASC),
  CONSTRAINT `fk_user_permissions`
    FOREIGN KEY (`permissions`)
    REFERENCES `greenhouse`.`permissions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`greenhouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`greenhouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`plot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`plot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plant` VARCHAR(45) NOT NULL,
  `id_grenhouse` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plot_greenhouse_idx` (`id_grenhouse` ASC),
  CONSTRAINT `fk_plot_greenhouse`
    FOREIGN KEY (`id_grenhouse`)
    REFERENCES `greenhouse`.`greenhouse` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `codename` VARCHAR(10) NOT NULL,
  `maxvalue` INT NOT NULL,
  `minvalue` INT NOT NULL,
  `type` VARCHAR(1) NOT NULL,
  `id_plot` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_idx` (`id_plot` ASC),
  CONSTRAINT `fk_sensor`
    FOREIGN KEY (`id_plot`)
    REFERENCES `greenhouse`.`plot` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`user_greenhouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`user_greenhouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_greenhouse` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_greenhouse_user_idx` (`id_user` ASC),
  INDEX `fk_user_greenhouse_greenhouse_idx` (`id_greenhouse` ASC),
  CONSTRAINT `fk_user_greenhouse_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `greenhouse`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_greenhouse_greenhouse`
    FOREIGN KEY (`id_greenhouse`)
    REFERENCES `greenhouse`.`greenhouse` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`actuator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`actuator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `codename` VARCHAR(10) NOT NULL,
  `type` VARCHAR(1) NOT NULL,
  `id_plot` INT NOT NULL,
  `id_sensor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actuator_plot_idx` (`id_plot` ASC),
  INDEX `fk_actuator_sensor_idx` (`id_sensor` ASC),
  CONSTRAINT `fk_actuator_plot`
    FOREIGN KEY (`id_plot`)
    REFERENCES `greenhouse`.`plot` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_actuator_sensor`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `greenhouse`.`sensor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`sensor_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`sensor_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `value` FLOAT(5,2) NOT NULL,
  `id_sensor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bitacora_sensor_idx` (`id_sensor` ASC),
  CONSTRAINT `fk_bitacora_sensor`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `greenhouse`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhouse`.`action_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenhouse`.`action_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `actions` TEXT NOT NULL,
  `id_user` INT NOT NULL,
  `id_actuator` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bitacoras_acciones_usuario_idx` (`id_user` ASC),
  INDEX `fk_action_logs_actuator_idx` (`id_actuator` ASC),
  CONSTRAINT `fk_action_logs_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `greenhouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_logs_actuator`
    FOREIGN KEY (`id_actuator`)
    REFERENCES `greenhouse`.`actuator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;